png, jpg to Webp
JIITODC/jiitodc.github.io pull request #30
Opened 2020-09-30 18:51 UTC by sarthakm21

The folders in Photos folder will also be included!

2020-10-01 05:57 UTC, humancalico requested changes
Thanks for the PR @sarthakm21. But this doesn't seem to convert any images. For an example you might want to refer to this - https://web.dev/use-imagemin-to-compress-images/#imagemin-npm-module

2020-10-01 06:03 UTC, aayushmau5 approved these changes

2020-10-01 06:05 UTC, aayushmau5 commented
> Thanks for the PR @sarthakm21. But this doesn't seem to convert any images. For an example you might want to refer to this - https://web.dev/use-imagemin-to-compress-images/#imagemin-npm-module

Wait lemme try.

2020-10-01 06:17 UTC, aayushmau5 requested changes
No image output.

2020-10-02 14:33 UTC, sarthakm21 commented
Hey @humancalico review this please....

2020-10-02 15:35 UTC, humancalico approved these changes
LGTM so far. Thanks @sarthakm21. Although some things can be added: 
1. Since we are going to run it as an `npm script` https://github.com/JIITODC/jiitodc.github.io/blob/d7e5ba9ba55bdd13cc23b4c87af7f585ace5e56a/package.json#L5-L13 so we would want it to run from the root directory so using `../static/Photos/**/*.{png,jpg}` wouldn't work in that case and can be changed to `static/Photos/**/*.{png,jpg}`. Same for `../static/Photos/webp/`
2. We would probably want to preserve the directory structure. This isn't possible in `imagemin` in the current state but a PR is open and we can use that. You can find more details in this stack overflow answer https://stackoverflow.com/a/62426873.

2020-10-03 07:53 UTC, sarthakm21 commented
preserveDirectories is not working with the imagemin-webp package. So, the directory structure is being preserved but the files are no longer getting converted into webp if i'm using this. Is there any other method to solve this @humancalico ?

2020-10-03 08:01 UTC, sarthakm21 commented
Also, the package won't allow absolute paths for some reason. So, I am unable to change the filepaths to `/static/Photos/`
Although, if the only concern is running the webp.js file as a npm script, this can be added in package.json
`"webp": "cd src && node webp.js"`
`npm run webp` works well from the root directory this way.

2020-10-03 08:25 UTC, humancalico commented
> preserveDirectories is not working with the imagemin-webp package. So, the directory structure is being preserved but the files are no longer getting converted into webp if i'm using this. Is there any other method to solve this @humancalico ?

Did you uninstall the existing `imagemin` package?.

> Also, the package won't allow absolute paths for some reason. So, I am unable to change the filepaths to `/static/Photos/`

You can use `./static/Photos`

> Although, if the only concern is running the webp.js file as a npm script, this can be added in package.json
> `"webp": "cd src && node webp.js"`
> `npm run webp` works well from the root directory this way.

Yeah you're right

2020-10-03 08:29 UTC, sarthakm21 commented
Yes I re-installed the 'npm install https://github.com/imagemin/imagemin#bfd7c547045f68ed92243c6a772f6265a08a687f --save-dev' package from the answer you mentioned. 
It is not working with imagemin-webp package for some reason.

2020-10-03 08:33 UTC, humancalico commented
Hmmm. Can you push the changes? I just tried it and it works for me.

2020-10-03 09:10 UTC, sarthakm21 commented
@humancalico the checks have failed for some reason now :(
What did I do wrong?

2020-10-03 09:12 UTC, humancalico commented
So, your script _is_ working for me. Do an `npm clean-install` and then test the script.

2020-10-03 09:16 UTC, humancalico commented
And the website is building locally as well. So your code seems fine. It's probably a problem with the CI.

2020-10-03 09:16 UTC, sarthakm21 commented
The images are still in their original format in my case. The files are being converted to .webp in your case?
Btw, the npm clean-install also yielded same results.

2020-10-03 09:17 UTC, humancalico commented
> The images are still in their original format in my case. The files are being converted to .webp in your case?

Yep

2020-10-03 09:18 UTC, sarthakm21 commented
So do I have to make some change now or leave it as it is?

2020-10-03 09:18 UTC, humancalico commented
Ohh wait no. It doesn't seem to work

2020-10-03 09:19 UTC, humancalico commented
> So do I have to make some change now or leave it as it is?

ig we can't do anything at this point. You can reset the commit and do a force-push I'll merge these changes as is.

2020-10-03 09:20 UTC, sarthakm21 commented
Alright

2020-10-03 09:57 UTC, humancalico commented
Thanks @sarthakm21!

2020-10-03 09:57 UTC, merged