Add missing links to team pages #39
JIITODC/jiitodc.github.io pull request #43
Opened 2020-10-05 01:45 UTC by LeoAlvarenga

I made some change as requested on issue #39, i tried to follow the images on issue post, if i did something wrong, let me know!

2020-10-05 01:47 UTC, LeoAlvarenga commented
if possible, lable it as valid to hacktoberfest

2020-10-05 08:06 UTC, humancalico requested changes
Looks great @LeoAlvarenga. Just a minor nitpick, can you use an icon or a symbol like `←`/`→`  instead of `<--`/`-->`?

2020-10-05 10:32 UTC, DelusionalOptimist commented
@LeoAlvarenga Thanks for working on this issue. Glad you understood what I was trying to say. :grin:
Adding to the changes requested by @humancalico, can you structure the pages in a format like this:-

Links on [team](https://jodc.vercel.app/team) page:- 
&larr;`2018-2019` &larr;`2019-2020`

Links on [team-2019](https://jodc.vercel.app/team-2019) page:-
&larr;`2018-2019` `2020-2021`&rarr;

Links on [team-2018](https://jodc.vercel.app/team-2018) page:-
`2019-2020`&rarr; `2020-2021`&rarr;

Basically this is like browsing pages of any site.

2020-10-05 19:32 UTC, LeoAlvarenga commented
Sure! i'll try to do those changes as soon as possible

2020-10-11 22:33 UTC, LeoAlvarenga commented
I just did the changes requested by you guys, hope you like!

2020-10-11 23:45 UTC, humancalico commented
Hey @LeoAlvarenga, can you fix these merge conflicts?

2020-10-11 23:45 UTC, humancalico commented
cc @DelusionalOptimist

2020-10-12 14:46 UTC, LeoAlvarenga commented
Sure, I'll try to solve it

2020-10-12 18:44 UTC, LeoAlvarenga commented
I think it's all set now!

2020-10-13 06:53 UTC, aayushmau5 commented on src/routes/team-2018.svelte
> +});
We removed this.Please fetch the latest commits.

2020-10-13 06:55 UTC, aayushmau5 requested changes

2020-10-13 06:55 UTC, aayushmau5 commented on src/routes/team.svelte
> -
Again. Fetch the latest commits.

2020-10-13 07:01 UTC, DelusionalOptimist commented on src/routes/team-2019.svelte
> +    <a rel="prefetch" href="/team"> &rarr; 2020-2021 </a>
Minor change: this should be `<a rel="prefetch" href="/team"> 2020-2021 &rarr;</a>`

2020-10-13 20:26 UTC, LeoAlvarenga commented on src/routes/team-2018.svelte
> +});
I'm trying to, but git says i'm already up to date

2020-10-15 15:09 UTC, aayushmau5 approved these changes
LGTM.

2020-10-15 18:36 UTC, DelusionalOptimist approved these changes
LGTM. Thanks @LeoAlvarenga :+1:.

2020-10-24 07:03 UTC, merged